USE HospitalDB;
GO

-- 1. View all patients
SELECT * FROM Patients;

-- 2. View all doctors and their specialties
SELECT DoctorName, Specialty FROM Doctors;

-- 3. View all appointments ordered by date
SELECT * FROM Appointments
ORDER BY AppointmentDate ASC;

-- 4. Count total number of patients
SELECT COUNT(*) AS TotalPatients FROM Patients;

-- 5. Count total number of appointments
SELECT COUNT(*) AS TotalAppointments FROM Appointments;

-- 6. Show all female patients only
SELECT * FROM Patients
WHERE Gender = 'Female';

-- 7. Show all appointments that cost more than 700
SELECT * FROM Appointments
WHERE Cost > 700
ORDER BY Cost DESC;

-- 8. Show all patients from Cairo
SELECT * FROM Patients
WHERE City = 'Cairo';

-- 9. Show each appointment with patient name and doctor name
SELECT 
    a.AppointmentID,
    p.PatientName,
    doc.DoctorName,
    a.AppointmentDate,
    a.Diagnosis,
    a.Cost
FROM Appointments a
JOIN Patients p   ON a.PatientID = p.PatientID
JOIN Doctors doc  ON a.DoctorID  = doc.DoctorID
ORDER BY a.AppointmentDate;

-- 10. How many appointments does each doctor have?
SELECT doc.DoctorName, COUNT(*) AS TotalAppointments
FROM Appointments a
JOIN Doctors doc ON a.DoctorID = doc.DoctorID
GROUP BY doc.DoctorName
ORDER BY TotalAppointments DESC;

-- 11. Total revenue generated by each department
SELECT d.DepartmentName, SUM(a.Cost) AS TotalRevenue
FROM Appointments a
JOIN Doctors doc      ON a.DoctorID     = doc.DoctorID
JOIN Departments d    ON doc.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName
ORDER BY TotalRevenue DESC;

-- 12. Most common diagnosis
SELECT Diagnosis, COUNT(*) AS Frequency
FROM Appointments
GROUP BY Diagnosis
ORDER BY Frequency DESC;

-- 13. Which city has the most patients?
SELECT City, COUNT(*) AS PatientCount
FROM Patients
GROUP BY City
ORDER BY PatientCount DESC;

-- 14. Average appointment cost per department
SELECT d.DepartmentName, AVG(a.Cost) AS AvgCost
FROM Appointments a
JOIN Doctors doc   ON a.DoctorID      = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName
ORDER BY AvgCost DESC;

-- 15. How many male vs female patients?
SELECT Gender, COUNT(*) AS Total
FROM Patients
GROUP BY Gender;

-- 16. Which month had the highest number of appointments?
SELECT FORMAT(AppointmentDate, 'yyyy-MM') AS Month,
       COUNT(*) AS TotalAppointments
FROM Appointments
GROUP BY FORMAT(AppointmentDate, 'yyyy-MM')
ORDER BY TotalAppointments DESC;

-- 17. Which patient paid the most in total?
SELECT p.PatientName, SUM(a.Cost) AS TotalPaid
FROM Appointments a
JOIN Patients p ON a.PatientID = p.PatientID
GROUP BY p.PatientName
ORDER BY TotalPaid DESC;

-- 18. Patient age pattern — how many patients per age group?
SELECT
  CASE
    WHEN Age < 30 THEN 'Under 30'
    WHEN Age BETWEEN 30 AND 50 THEN '30 to 50'
    ELSE 'Over 50'
  END AS AgeGroup,
  COUNT(*) AS PatientCount
FROM Patients
GROUP BY
  CASE
    WHEN Age < 30 THEN 'Under 30'
    WHEN Age BETWEEN 30 AND 50 THEN '30 to 50'
    ELSE 'Over 50'
  END;

  -- 19. Doctor with the highest total revenue earned
SELECT 
    doc.DoctorName,
    d.DepartmentName,
    COUNT(a.AppointmentID) AS Appointments,
    SUM(a.Cost)            AS TotalRevenue
FROM Appointments a
JOIN Doctors doc   ON a.DoctorID      = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
GROUP BY doc.DoctorName, d.DepartmentName
ORDER BY TotalRevenue DESC;

-- 20. Most expensive and cheapest appointment per department
SELECT 
    d.DepartmentName,
    MAX(a.Cost) AS MostExpensive,
    MIN(a.Cost) AS Cheapest
FROM Appointments a
JOIN Doctors doc   ON a.DoctorID       = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName;

-- 21. Which diagnosis generates the most total revenue?
SELECT 
    Diagnosis,
    COUNT(*)    AS TimesOccured,
    SUM(Cost)   AS TotalRevenue,
    AVG(Cost)   AS AvgCostPerVisit
FROM Appointments
GROUP BY Diagnosis
ORDER BY TotalRevenue DESC;

-- 22. Rank doctors by number of appointments using RANK()
SELECT 
    doc.DoctorName,
    d.DepartmentName,
    COUNT(a.AppointmentID) AS TotalAppointments,
    RANK() OVER (ORDER BY COUNT(a.AppointmentID) DESC) AS DoctorRank
FROM Appointments a
JOIN Doctors doc   ON a.DoctorID       = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
GROUP BY doc.DoctorName, d.DepartmentName;

-- 23. Find patients who visited more than once
SELECT 
    p.PatientName,
    COUNT(a.AppointmentID) AS TotalVisits
FROM Appointments a
JOIN Patients p ON a.PatientID = p.PatientID
GROUP BY p.PatientName
HAVING COUNT(a.AppointmentID) > 1
ORDER BY TotalVisits DESC;

-- 24. Compare each department's revenue to the overall average
SELECT 
    d.DepartmentName,
    SUM(a.Cost) AS DeptRevenue,
    AVG(SUM(a.Cost)) OVER () AS OverallAvgRevenue,
    SUM(a.Cost) - AVG(SUM(a.Cost)) OVER () AS DiffFromAverage
FROM Appointments a
JOIN Doctors doc   ON a.DoctorID       = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName;

-- 25. Running total of revenue over time
SELECT 
    AppointmentDate,
    Cost,
    SUM(Cost) OVER (ORDER BY AppointmentDate) AS RunningTotalRevenue
FROM Appointments
ORDER BY AppointmentDate;

-- 26. Find the top 3 most expensive appointments with full details
SELECT TOP 3
    p.PatientName,
    doc.DoctorName,
    d.DepartmentName,
    a.Diagnosis,
    a.Cost,
    a.AppointmentDate
FROM Appointments a
JOIN Patients p    ON a.PatientID      = p.PatientID
JOIN Doctors doc   ON a.DoctorID       = doc.DoctorID
JOIN Departments d ON doc.DepartmentID = d.DepartmentID
ORDER BY a.Cost DESC;

-- 27. Patients who were diagnosed with Hypertension or Heart related issues
SELECT DISTINCT
    p.PatientName,
    p.Age,
    p.City,
    a.Diagnosis
FROM Appointments a
JOIN Patients p ON a.PatientID = p.PatientID
WHERE a.Diagnosis LIKE '%Heart%' 
   OR a.Diagnosis LIKE '%Hypertension%'
ORDER BY p.Age DESC;

-- 28. Monthly revenue growth compared to previous month
SELECT 
    Month,
    MonthlyRevenue,
    LAG(MonthlyRevenue) OVER (ORDER BY Month) AS PrevMonthRevenue,
    MonthlyRevenue - LAG(MonthlyRevenue) OVER (ORDER BY Month) AS RevenueGrowth
FROM (
    SELECT 
        FORMAT(AppointmentDate, 'yyyy-MM') AS Month,
        SUM(Cost) AS MonthlyRevenue
    FROM Appointments
    GROUP BY FORMAT(AppointmentDate, 'yyyy-MM')
) AS MonthlyData
ORDER BY Month;